/**
 * Builds enriched lesson content from units.js for seed + local demo.
 * Run: node scripts/enrichLessons.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { UNITS } from '../src/data/units.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

function sessionFlow(grammar) {
  return [
    { minutes: 5, step: 'Warm-up', detail: `Activate prior knowledge related to: ${grammar}.` },
    { minutes: 10, step: 'Teach', detail: `Explain form and meaning of ${grammar} with board examples.` },
    { minutes: 15, step: 'Guided practice', detail: 'Complete the in-lesson worksheet together.' },
    { minutes: 10, step: 'Review quiz', detail: 'Quick check of this lesson + last 1–2 lessons.' },
    { minutes: 10, step: 'Production', detail: 'Student writes or speaks using the target grammar.' },
    { minutes: 5, step: 'Assign homework', detail: 'Explain homework expectations for next session.' },
  ]
}

function commonMistakes(grammar, arabic) {
  return [
    {
      wrong: 'Transferring Arabic word order into English.',
      tip: `Keep English SVO while teaching ${grammar} (${arabic || 'see Arabic label'}).`,
    },
    {
      wrong: 'Mixing tense markers (time words vs verb form).',
      tip: 'Highlight time expressions on the board next to the correct form.',
    },
    {
      wrong: 'Over-translating every sentence.',
      tip: 'Allow Arabic for meaning check, then return to English production.',
    },
  ]
}

function toWorksheet(exercises) {
  const items = (exercises || []).map((ex, i) => ({
    id: `ws-${i + 1}`,
    type: 'fill',
    prompt: ex.q,
    answer: ex.a,
  }))
  items.push({
    id: 'ws-prod',
    type: 'write',
    prompt: 'Write 2 original sentences using today’s grammar.',
    answer: '',
  })
  return items
}

function toHomework(exercises, grammar) {
  const base = (exercises || []).map((ex, i) => ({
    id: `hw-${i + 1}`,
    type: 'fill',
    prompt: ex.q.replace('____', '__________'),
    answer: ex.a,
  }))
  base.push({
    id: 'hw-reflect',
    type: 'write',
    prompt: `Explain in one sentence when we use: ${grammar}.`,
    answer: '',
  })
  base.push({
    id: 'hw-prod',
    type: 'write',
    prompt: 'Write a short paragraph (4–5 sentences) using today’s grammar.',
    answer: '',
  })
  return base
}

function toQuizBank(quiz, exercises) {
  const bank = (quiz || []).map((q, i) => ({
    id: `qb-mcq-${i + 1}`,
    type: 'mcq',
    prompt: q.q,
    options: q.options,
    correct: q.correct,
  }))
  ;(exercises || []).forEach((ex, i) => {
    bank.push({
      id: `qb-fill-${i + 1}`,
      type: 'fill',
      prompt: ex.q,
      answer: ex.a,
    })
  })
  return bank
}

function enrichUnit(grade, unit) {
  return {
    grade: String(grade),
    unit_number: unit.unit,
    theme: unit.theme,
    grammar: unit.grammar,
    arabic: unit.arabic || '',
    explanation: unit.explanation || '',
    visual: unit.visual || [],
    objectives: [
      `Understand form and meaning of ${unit.grammar}.`,
      `Use ${unit.grammar} accurately in controlled practice.`,
      `Produce at least two original sentences with ${unit.grammar}.`,
    ],
    session_flow: sessionFlow(unit.grammar),
    common_mistakes: commonMistakes(unit.grammar, unit.arabic),
    teacher_notes: `Focus on clarity over speed. Recycle ${unit.grammar} with personal examples from the student’s life.`,
    worksheet: toWorksheet(unit.exercises),
    homework: toHomework(unit.exercises, unit.grammar),
    quiz_bank: toQuizBank(unit.quiz, unit.exercises),
  }
}

const lessons = []
for (const grade of Object.keys(UNITS)) {
  for (const unit of UNITS[grade]) {
    lessons.push(enrichUnit(grade, unit))
  }
}

const outPath = join(__dirname, '../src/data/enrichedLessons.js')
const file = `/** Auto-generated by scripts/enrichLessons.mjs — do not hand-edit. */\nexport const ENRICHED_LESSONS = ${JSON.stringify(lessons, null, 2)}\n`
writeFileSync(outPath, file)
console.log(`Wrote ${lessons.length} lessons → ${outPath}`)
